<?php
function drupdown_soundcloud_drupdown_url_patterns() {
  $patterns['/soundcloud\.com\//'] = array(
    'function' => 'drupdown_soundcloud_callback',
    'weight' => 90,
  );
  return $patterns;
}

function drupdown_soundcloud_callback($text, $url, $settings, $matches) {
  $result = drupal_json_decode(drupal_http_request('http://api.soundcloud.com/resolve.json?client_id=c21bf5b71f7bde9d894df5f65582bbe9&url=' . $url)->data);
  return '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="http://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F' . $result['id'] . '&amp;auto_play=false&amp;show_artwork=false&amp;color=ff7700"></iframe>';
}
