<?php
function drupdown_menu() {
  return array(
    'drupdown/playground' => array(
      'title' => t('Drupdown Playground'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('drupdown_playground'),
      'access callback' => TRUE,
    ),
    'admin/config/content/drupdown' => array(
      'title' => t('Drupdown'),
      'description' => t('Adminsiter Drupdown settings.'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('drupdown_settings'),
      'access arguments' => array('administer site configuration'),
    ),
  );
}

function drupdown_settings($form, $form_state) {
  $form['image_formats'] = array(
    '#type' => 'fieldset',
    '#title' => t('Available image styles'),
    '#description' => t('Image styles which are available in the drupdown editor.'),
    'drupdown_styles' => array(
      '#type' => 'checkboxes',
      '#options' => array('original' => 'original'),
      '#default_value' => variable_get('drupdown_styles', array()),
    ),
  );
  foreach (image_styles() as $id => $style) {
    $form['image_formats']['drupdown_styles']['#options'][$id] = $style['name'];
  }
  return system_settings_form($form);
}

function drupdown_init() {
  drupal_add_js(array('drupdown' => array('styles' => variable_get('drupdown_styles', array()))), 'setting');
}

function drupdown_ace_plugins_alter(&$plugins) {
  $plugins['modes']['drupdown'] = array(
    'title' => t('Drupdown'),
    'module' => 'ace/mode/drupdown',
    'attached' => array(
      'js' => array(
        drupal_get_path('module', 'drupdown') . '/js/mode-drupdown.js',
      ),
    ),
  );
  $plugins['toolbars']['drupdown'] = array(
    'title' => t('Drupdown'),
    'module' => 'ace/toolbar/drupdown',
    'attached' => array(
      'js' => array(
        drupal_get_path('module', 'drupdown') . '/js/toolbar-drupdown.js',
      ),
      'css' => array(
        drupal_get_path('module', 'drupdown') . '/drupdown.css',
      ),
      'library' => array(
        array('system', 'ui.dialog'),
        array('system', 'ui.autocomplete'),
        array('system', 'effects.fade'),
      ),
    ),
  );
}

function drupdown_playground($form, &$form_state) {
  $content = drupdown_to_html(@$form_state['values']['input']);
  $form = array(
    'input' => array(
      '#type' => 'textarea',
      '#ace' => TRUE,
      '#ace_format' => 'drupdown',
    ),
    'transform' => array(
      '#type' => 'button',
      '#value' => t('Transform'),
      '#ajax' => array(
        'wrapper' => 'drupdown-playground-output',
        'callback' => 'drupdown_playground_callback',
        'effect' => 'fade',
      ),
    ),
    'output' => array(
      '#prefix' => '<div id="drupdown-playground-output">',
      '#suffix' => '</div>',
      'formatted' => array(
        '#prefix' => '<div class="formatted-output clearfix">',
        '#suffix' => '</div>',
        '#markup' => $content, 
      ),
      'raw' => array(
        '#prefix' => '<pre class="raw-output">',
        '#suffix' => '</pre>',
        '#markup' => htmlentities($content),
      ),
    ),
  );
  return $form;
}

/**
 * Implements hook_filter_info().
 */
function drupdown_filter_info() {
  $filters['filter_drupdown'] = array(
    'title' => t('Drupdown'),
    'description' => t('Extended Markdown with Drupal flavor.'),
    'process callback' => '_drupdown_process',
  );
  return $filters;
}

/**
 * Main process callback.
 */
function _drupdown_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  return drupdown_to_html($text);
}

function drupdown_playground_callback($form, $form_state) {
  return $form['output'];
}

function drupdown_to_html($input) {
  module_load_include('inc', 'drupdown', 'markdown');
  module_load_include('inc', 'drupdown', 'drupdown');
  $parser = new DrupdownParser();
	return $parser->transform($input);
}

function drupdown_process_reference($text, $url, $title, $modifier) {
  // remove leading slashes
  $url = preg_replace('/^\//', '', $url);
  $classes = array(
    '!' => '.drupdown-center',
    '>' => '.drupdown-right',
    '<' => '.drupdown-left',
  );
  $patterns = drupdown_url_patterns();
  foreach ($patterns as $pattern => $callback) {
    if (preg_match($pattern, $url, $matches)) {
      $result = call_user_func_array($callback, array($text, $url, $title, $modifier, $matches));
      if (strlen($result) > 0) {
        return $result;
      }
    }
  }
}

function drupdown_url_patterns() {
  $patterns = array();
  $patterns['/^(.*?)(\:\/\/?).*\.(png|jpg|jpeg|gif)$/i'] = '_drupdown_image_callback';
  $patterns['/.*/'] = '_drupdown_link_callback';
  return $patterns;
}

function _drupdown_image_callback($text, $url, $title, $modifier, $matches) {
  $protocol = $matches[1];
  if ($protocol == 'original') {
    $protocol = 'public';
    $url = str_replace('original://', 'public://', $url);
  }
  if (!in_array($protocol, array('http', 'https', 'public', 'private'))) {
    if (in_array($protocol, array_keys(image_styles()))) {
      $url = image_style_url($protocol, str_replace($protocol, 'public', $url));
    }
    else {
      return FALSE;
    }
  }

  if ($modifier == '') {
    return FALSE;
  }

  $classes = array(
    '!' => 'drupdown-center',
    '<' => 'drupdown-left',
    '>' => 'drupdown-right',
  );

  return '<div>' . theme('image', array(
    'path' => $url,
    'title' => $title,
    'alt' => $text,
  )) . '</div>';
}

function _drupdown_link_callback($text, $url, $title, $modifier, $matches) {
  return l($text, $url, array(
    '#attributes' => array(
      'title' => $title,
    ),
  ));
}

function drupdown_element_info_alter(&$types) {
  $types['managed_file']['#after_build'][] = 'drupdown_file_element_process';
}

function drupdown_file_element_process($element) {
  if (array_key_exists('#file', $element) && is_object($element['#file'])) {
    if (in_array('image_field_widget_process', $element['#process'])) {
      $element['file_uri'] = array(
        '#type' => 'hidden',
        '#value' => str_replace('public://', 'original://', $element['#file']->uri),
        '#attributes' => array('class' => array('drupdown-resource')),
      );
    } else {
      $element['file_uri'] = array(
        '#type' => 'hidden',
        '#value' => $element['#file']->uri,
        '#attributes' => array('class' => array('drupdown-resource')),
      );
    }
  }
  return $element;
}
