<?php
function drupdown_vimeo_drupdown_url_patterns() {
  $patterns['/vimeo\.com\/([0-9]+)/'] = array(
    'function' => 'drupdown_vimeo_callback',
    'weight' => 90,
    'classes' => array('drupdown-vimeo', 'drupdown-video'),
  );
  return $patterns;
}

function drupdown_vimeo_callback($text, $url, $settings, $matches) {
  return '<iframe
    class="drupdown-vimeo"
    src="http://player.vimeo.com/video/' . $matches[1] . '?title=0&amp;byline=0&amp;portrait=0"></iframe>';
}
