<?php
function drupdown_picasa_drupdown_url_patterns() {
  $patterns['/picasaweb\.google\.com\/(.+?)\/([^?&]+)/'] = array(
    'function' => 'drupdown_picasa_gallery_callback',
    'weight' => 90,
    'classes' => array('drupdown-picasa-gallery'),
  );
  return $patterns;
}

function drupdown_picasa_gallery_callback($text, $url, $settings, $matches) {
  $user_id = $matches[1];
  $album = $matches[2];
  $url = 'https://picasaweb.google.com/data/feed/api/user/' . $user_id . '/album/' . $album . '?alt=json';
  $result = drupal_http_request($url);
  $data = drupal_json_decode($result->data);
  if (!$data) {
    return;
  }
  $list = array();
  foreach ($data['feed']['entry'] as $img) {
    $list[] = l(theme('image', array(
      'path' => $img['media$group']['media$thumbnail'][0]['url'],
      'title' => $img['title']['$t'],
    )), $img['content']['src'], array(
      'attributes' => array(
        'class' => array('colorbox'),
        'rel' => $img['gphoto$albumid']['$t'],
        'title' => $img['title']['$t'],
      ),
      'html' => TRUE,
    ));
  }
  return theme('item_list', array(
    'items' => $list,
    'attributes' => array(
      'class' => 'drupdown-picasa-album',
    ),
  ));
}

function drupdown_picasa_init() {
  drupal_add_css(drupal_get_path('module', 'drupdown_picasa') . '/drupdown_picasa.css');
}
